<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8f592e93-2261-41aa-b232-5b916a31a999</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartTaxi.Application\SmartTaxi.Application.csproj" />
    <ProjectReference Include="..\SmartTaxi.Infrastructure\SmartTaxi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
