/// Referentiel des annonceurs publicitaires.
table Annonceur
	lineageTag: 619aec48-51e7-4bd0-9bf0-1fc7422ad5cb

	/// Identifiant technique de l annonceur.
	column AnnonceurID
		dataType: string
		isHidden
		lineageTag: 78704ba8-9e0d-4d8f-ab2a-8ff7f27450df
		summarizeBy: none
		sourceColumn: AnnonceurID

	/// Nom de l annonceur.
	column Annonceur
		dataType: string
		lineageTag: e92b0b5f-8d44-4a22-92f4-b2d148a67b1f
		summarizeBy: none
		sourceColumn: Annonceur

	/// Ville de l annonceur.
	column Ville
		dataType: string
		lineageTag: 9e283d72-f129-48ed-9bee-9ec660f8c370
		summarizeBy: none
		sourceColumn: Ville

	partition Annonceur = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "\annonceur.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"AnnonceurID", type text}, {"Annonceur", type text}, {"Ville", type text}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table

