/// Referentiel des villes couvertes et de leur poids dans les objectifs.
table Ville
	lineageTag: 92a246d2-61b1-43c5-ac57-4c400622e1c6

	/// Nom de la ville.
	column Ville
		dataType: string
		lineageTag: a5c8cc67-72e3-41f0-a3ae-24d57338bd21
		summarizeBy: none
		sourceColumn: Ville

	/// Contribution de la ville a l objectif annuel, en TND.
	column PoidsObjectif
		dataType: double
		isHidden
		formatString: #,0.00
		lineageTag: 52db0003-348e-41bb-8f99-b1970f25e98a
		summarizeBy: none
		sourceColumn: PoidsObjectif

	/// Part de la ville dans l objectif annuel.
	column PartObjectif
		dataType: double
		formatString: 0.0%
		lineageTag: 29007a56-3dcc-4cc9-9bfe-9658fed63027
		summarizeBy: none
		sourceColumn: PartObjectif

	partition Ville = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "\ville.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"Ville", type text}, {"PoidsObjectif", type number}, {"PartObjectif", type number}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table

