using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SmartTaxi.Domain.Identity.Entities;

namespace SmartTaxi.Infrastructure.Persistence.Configurations;

public sealed class SessionConfiguration : IEntityTypeConfiguration<UserSession>
{
    public void Configure(EntityTypeBuilder<UserSession> builder)
    {
        builder.ToTable("Sessions");

        builder.HasKey(session => session.Id);
        builder.Property(session => session.Id).ValueGeneratedNever();

        builder.Property(session => session.UserId).IsRequired();
        builder.HasIndex(session => session.UserId);

        builder.Property(session => session.CreatedAt).IsRequired();
        builder.Property(session => session.LastActivityAt).IsRequired();
        builder.Property(session => session.ExpiresAt).IsRequired();

        builder.Property(session => session.RevokedReason)
            .HasConversion<string>()
            .HasMaxLength(50);

        builder.Property(session => session.DeviceLabel).HasMaxLength(200);

        // Application-managed optimistic concurrency token (regenerated by the
        // domain on every mutation — see UserSession.ConcurrencyStamp) rather than
        // a database-computed one: this is what makes "two concurrent refresh
        // attempts cannot both succeed" enforceable. The whole session (root + its
        // owned tokens) is always loaded and saved together, so the root's own
        // stamp is sufficient to detect that someone else already modified this
        // session since it was read. The second SaveChanges to touch the same row
        // loses the race and fails with DbUpdateConcurrencyException, which the
        // repository catches.
        builder.Property(session => session.ConcurrencyStamp).IsConcurrencyToken();

        // Configured through the RefreshTokens property (not a field-name string,
        // unlike 2a's UserRoleAssignment) specifically so that server-side LINQ
        // queries like ".Where(s => s.RefreshTokens.Any(t => t.TokenHash == hash))"
        // — needed to find a session by any token in its rotation chain — can be
        // translated to SQL: EF matches query expressions against the exact member
        // used to configure the navigation. Materialization still goes through the
        // private _refreshTokens field (matched by EF's naming convention) via
        // UsePropertyAccessMode below, so the collection stays fully encapsulated.
        builder.OwnsMany(session => session.RefreshTokens, tokens =>
        {
            tokens.ToTable("RefreshTokens");
            tokens.WithOwner().HasForeignKey(token => token.SessionId);
            tokens.HasKey(token => token.Id);
            tokens.Property(token => token.Id).ValueGeneratedNever();

            tokens.Property(token => token.TokenHash).HasMaxLength(500).IsRequired();
            tokens.HasIndex(token => token.TokenHash).IsUnique();

            tokens.Property(token => token.CreatedAt).IsRequired();
            tokens.Property(token => token.ExpiresAt).IsRequired();
        });

        builder.Navigation(session => session.RefreshTokens).UsePropertyAccessMode(PropertyAccessMode.Field);
    }
}
