apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarttaxi-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: smarttaxi-api

  template:
    metadata:
      labels:
        app: smarttaxi-api

    spec:
      securityContext:
        runAsNonRoot: true

      containers:
        - name: smarttaxi-api

          image: 397291427673.dkr.ecr.eu-north-1.amazonaws.com/smarttaxi-api:dev

          ports:
            - containerPort: 8080

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: smarttaxi-config
                  key: ASPNETCORE_ENVIRONMENT

            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: smarttaxi-config
                  key: Jwt__Issuer

            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: smarttaxi-config
                  key: Jwt__Audience

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: smarttaxi-secrets
                  key: JWT_KEY

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smarttaxi-secrets
                  key: POSTGRES_PASSWORD

            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Port=5432;Database=smarttaxi;Username=smarttaxi_user;Password=$(POSTGRES_PASSWORD)"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
